name: munchkin_notebook
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: ^6.3.0
  flutter_bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  pin_code_fields: ^7.4.0

dev_dependencies:
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: munchkin
      fonts:
        - asset: assets/fonts/munchkin.ttf

    - family: academy
      fonts:
        - asset: assets/fonts/academy.ttf
  assets:
    - assets/images/
